
    create table bicycles (
        gear_count integer not null,
        is_foldable boolean not null,
        id bigint generated by default as identity,
        vehicle_id bigint not null unique,
        brake_type varchar(50) not null check ((brake_type in ('DRUM','DISC'))),
        suspension_type varchar(50) not null check ((suspension_type in ('NONE','SPRING','AIR'))),
        primary key (id)
    );

    create table cars (
        displacement_cc integer not null,
        door_count integer not null,
        license_plate varchar(7) not null unique,
        id bigint generated by default as identity,
        vehicle_id bigint not null unique,
        primary key (id)
    );

    create table motorcycles (
        displacement_cc integer not null,
        license_plate varchar(7) not null unique,
        id bigint generated by default as identity,
        vehicle_id bigint not null unique,
        primary key (id)
    );

    create table vehicles (
        production_year integer not null,
        wheel_count integer not null,
        id bigint generated by default as identity,
        brand varchar(50) not null,
        category varchar(50) not null check ((category in ('STREET','SUV','OFF_ROAD','SEDAN','MOTOCROSS','ENDURO','RACING','MOUNTAIN_BIKE','SCOOTER','PICK_UP'))),
        color varchar(50) not null,
        fuel_type varchar(50) not null check ((fuel_type in ('LPG','DIESEL','PETROL','HYBRID','ELECTRIC','NONE'))),
        model varchar(50) not null,
        vehicle_type varchar(50) not null check ((vehicle_type in ('CAR','MOTORCYCLE','BICYCLE'))),
        primary key (id)
    );

    alter table if exists bicycles 
       add constraint fk_vehicle_bicycle 
       foreign key (vehicle_id) 
       references vehicles;

    alter table if exists cars 
       add constraint fk_vehicle_car 
       foreign key (vehicle_id) 
       references vehicles;

    alter table if exists motorcycles 
       add constraint fk_vehicle_motorcycle 
       foreign key (vehicle_id) 
       references vehicles;
