
    create table bicycles (
        gears integer not null,
        is_foldable boolean not null,
        id bigint generated by default as identity,
        vehicle_id bigint not null unique,
        break_type varchar(50) not null check ((break_type in ('TAMBURO','DISCO'))),
        suspension_type varchar(50) not null check ((suspension_type in ('NESSUNA','MOLLA','ARIA'))),
        primary key (id)
    );

    create table cars (
        cc integer not null,
        door_number integer not null,
        license_plate varchar(7) not null unique,
        id bigint generated by default as identity,
        vehicle_id bigint not null unique,
        primary key (id)
    );

    create table motorcycles (
        cc integer not null,
        license_plate varchar(7) not null unique,
        id bigint generated by default as identity,
        vehicle_id bigint not null unique,
        primary key (id)
    );

    create table vehicles (
        production_year integer not null,
        wheel_number integer not null,
        id bigint generated by default as identity,
        brand varchar(50) not null,
        category varchar(50) not null check ((category in ('STRADALE','SUV','FUORISTRADA','BERLINA','MOTOCROSS','ENDURO','CORSA','MOUNTAIN_BIKE','SCOOTER','PICK_UP'))),
        color varchar(50) not null,
        fuel_type varchar(50) not null check ((fuel_type in ('GPL','DIESEL','BENZINA','HYBRID','ELETTRICA','NESSUNA'))),
        model varchar(50) not null,
        vehicle_type varchar(50) not null check ((vehicle_type in ('CAR','MOTORCYCLE','BICYCLE'))),
        primary key (id)
    );

    alter table if exists bicycles 
       add constraint fk_vehicle_bicycle 
       foreign key (vehicle_id) 
       references vehicles;

    alter table if exists cars 
       add constraint fk_vehicle_car 
       foreign key (vehicle_id) 
       references vehicles;

    alter table if exists motorcycles 
       add constraint fk_vehicle_motorcycle 
       foreign key (vehicle_id) 
       references vehicles;
