
    create table bicycles (
        gear_count integer not null,
        is_foldable boolean not null,
        brake_type_id bigint not null,
        id bigint generated by default as identity,
        suspension_type_id bigint not null,
        vehicle_id bigint not null unique,
        primary key (id)
    );

    create table brake_types (
        id bigint generated by default as identity,
        brake_type varchar(50) not null unique,
        primary key (id)
    );

    create table cars (
        displacement_cc integer not null,
        door_count integer not null,
        license_plate varchar(7) not null unique,
        id bigint generated by default as identity,
        vehicle_id bigint not null unique,
        primary key (id)
    );

    create table category (
        id bigint generated by default as identity,
        category varchar(50) not null unique,
        primary key (id)
    );

    create table fuel_types (
        id bigint generated by default as identity,
        fuel varchar(50) not null unique,
        primary key (id)
    );

    create table motorcycles (
        displacement_cc integer not null,
        license_plate varchar(7) not null unique,
        id bigint generated by default as identity,
        vehicle_id bigint not null unique,
        primary key (id)
    );

    create table suspension_types (
        id bigint generated by default as identity,
        suspension_type varchar(50) not null unique,
        primary key (id)
    );

    create table system_message (
        msg varchar(100) not null,
        code varchar(255) not null,
        primary key (code)
    );

    create table vehicle_types (
        id bigint generated by default as identity,
        vehicle_type varchar(50) not null unique,
        primary key (id)
    );

    create table vehicles (
        production_year integer not null,
        wheel_count integer not null,
        category_id bigint not null,
        fuel_type_id bigint not null,
        id bigint generated by default as identity,
        vehicle_type_id bigint not null,
        brand varchar(50) not null,
        color varchar(50) not null,
        model varchar(50) not null,
        primary key (id)
    );

    alter table if exists bicycles 
       add constraint fk_vehicle_braketype 
       foreign key (brake_type_id) 
       references brake_types;

    alter table if exists bicycles 
       add constraint fk_vehicle_suspensiontype 
       foreign key (suspension_type_id) 
       references suspension_types;

    alter table if exists bicycles 
       add constraint fk_vehicle_bicycle 
       foreign key (vehicle_id) 
       references vehicles;

    alter table if exists cars 
       add constraint fk_vehicle_car 
       foreign key (vehicle_id) 
       references vehicles;

    alter table if exists motorcycles 
       add constraint fk_vehicle_motorcycle 
       foreign key (vehicle_id) 
       references vehicles;

    alter table if exists vehicles 
       add constraint fk_vehicle_category 
       foreign key (category_id) 
       references category;

    alter table if exists vehicles 
       add constraint fk_vehicle_fueltype 
       foreign key (fuel_type_id) 
       references fuel_types;

    alter table if exists vehicles 
       add constraint fk_vehicle_vehicletype 
       foreign key (vehicle_type_id) 
       references vehicle_types;
